In [20]:
import numpy as np

In [16]:
import pandas as pd

In [17]:
from sklearn.naive_bayes import GaussianNB

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
from sklearn.metrics import accuracy_score

In [21]:
df = pd.read_csv('diabetes.csv')

In [22]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data.shape

(768, 9)

In [25]:
data_X = data[:,1:]

In [26]:
data_X

array([[148.   ,  72.   ,  35.   , ...,   0.627,  50.   ,   1.   ],
       [ 85.   ,  66.   ,  29.   , ...,   0.351,  31.   ,   0.   ],
       [183.   ,  64.   ,   0.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [121.   ,  72.   ,  23.   , ...,   0.245,  30.   ,   0.   ],
       [126.   ,  60.   ,   0.   , ...,   0.349,  47.   ,   1.   ],
       [ 93.   ,  70.   ,  31.   , ...,   0.315,  23.   ,   0.   ]])

In [27]:
data_X.shape

(768, 8)

In [28]:
data_Y = data[:,0]

In [29]:
data_Y

array([ 6.,  1.,  8.,  1.,  0.,  5.,  3., 10.,  2.,  8.,  4., 10., 10.,
        1.,  5.,  7.,  0.,  7.,  1.,  1.,  3.,  8.,  7.,  9., 11., 10.,
        7.,  1., 13.,  5.,  5.,  3.,  3.,  6., 10.,  4., 11.,  9.,  2.,
        4.,  3.,  7.,  7.,  9.,  7.,  0.,  1.,  2.,  7.,  7.,  1.,  1.,
        5.,  8.,  7.,  1.,  7.,  0.,  0.,  0.,  2.,  8.,  5.,  2.,  7.,
        5.,  0.,  2.,  1.,  4.,  2.,  5., 13.,  4.,  1.,  1.,  7.,  5.,
        0.,  2.,  3.,  2.,  7.,  0.,  5.,  2., 13.,  2., 15.,  1.,  1.,
        4.,  7.,  4.,  2.,  6.,  2.,  1.,  6.,  1.,  1.,  1.,  0.,  1.,
        2.,  1.,  1.,  4.,  3.,  0.,  3.,  8.,  1.,  4.,  7.,  4.,  5.,
        5.,  4.,  4.,  0.,  6.,  2.,  5.,  0.,  1.,  3.,  1.,  1.,  0.,
        4.,  9.,  3.,  8.,  2.,  2.,  0.,  0.,  0.,  5.,  3.,  5.,  2.,
       10.,  4.,  0.,  9.,  2.,  5.,  2.,  1.,  4.,  9.,  1.,  8.,  7.,
        2.,  1.,  2., 17.,  4.,  7.,  0.,  2.,  0.,  6.,  3.,  4.,  4.,
        3.,  6.,  6.,  2.,  1.,  2.,  8.,  6.,  0.,  5.,  5.,  6

In [30]:
x_train, x_test, y_train, y_test = train_test_split(data_X, data_Y, test_size = 0.2)

In [31]:
np.unique(y_train)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 15., 17.])

In [32]:
model = GaussianNB()
model.fit(train_datadsc, train_maindata)

GaussianNB(priors=None, var_smoothing=1e-09)

In [33]:
prediction = model.predict(test_datadsc)

In [34]:
prediction

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0.])

In [35]:
acc = accuracy_score(test_maindata, prediction)

In [36]:
acc

1.0